/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 19:23:00 UTC 
 * Modify at your own risk.
 */

package com.ssm.quadrah.diymarket.entity.layoutinfoendpoint.model;

/**
 * Model definition for LayoutInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the layoutinfoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class LayoutInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float height;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imageUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer layoutId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float width;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer workPkgId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getHeight() {
    return height;
  }

  /**
   * @param height height or {@code null} for none
   */
  public LayoutInfo setHeight(java.lang.Float height) {
    this.height = height;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImageUrl() {
    return imageUrl;
  }

  /**
   * @param imageUrl imageUrl or {@code null} for none
   */
  public LayoutInfo setImageUrl(java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLayoutId() {
    return layoutId;
  }

  /**
   * @param layoutId layoutId or {@code null} for none
   */
  public LayoutInfo setLayoutId(java.lang.Integer layoutId) {
    this.layoutId = layoutId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getWidth() {
    return width;
  }

  /**
   * @param width width or {@code null} for none
   */
  public LayoutInfo setWidth(java.lang.Float width) {
    this.width = width;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWorkPkgId() {
    return workPkgId;
  }

  /**
   * @param workPkgId workPkgId or {@code null} for none
   */
  public LayoutInfo setWorkPkgId(java.lang.Integer workPkgId) {
    this.workPkgId = workPkgId;
    return this;
  }

  @Override
  public LayoutInfo set(String fieldName, Object value) {
    return (LayoutInfo) super.set(fieldName, value);
  }

  @Override
  public LayoutInfo clone() {
    return (LayoutInfo) super.clone();
  }

}
